name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

template: |
  ## 📦 Release $NEXT_PATCH_VERSION

  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement

  - title: '🐛 Bug Fixes'
    labels:
      - bug

  - title: '🧹 Maintenance'
    labels:
      - chore
      - refactor

  - title: '📚 Documentation'
    labels:
      - docs

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - feature
      - enhancement
  patch:
    labels:
      - patch
      - bug
      - chore
  default: patch

exclude-labels:
  - skip-release-notes

replacers: []
